### PR TITLE
Adds Items & Audio Online Links (WIP)

### PR DESCRIPTION
**Pull request by CDAGaming**
To-Do:
- Re-Change Links Based on Item Renames

### CODE REVIEW

**Comment by Lord-Haji** [comment]
Further Updates #11

**Comment by sanguneo** [comment]
I think using online resource isn't good idea, It only just reducing application size, but traffic will made continuesly and it can be cause of speed issue.

**Comment by sanguneo** [comment]
And also using 'https protocol' is for slower and heavier than http.

**Comment by jjskuld** [comment]
I think it is probably OK to switch to online resources. In most cases the images will be cached by the browser on first access, so you should not see too much of a slowdown.  If we do see any performance issue we can revert this change.

**Comment by CDAGaming** [comment]
@jjskuld This was clearly marked WIP, as there are still script errors that have to be addressed, please revert to continue work on to fix these script issues

**Comment by CDAGaming** [comment]
Appveyor only builds from vs so it wouldn't detect any errors, but there are at least 164 errors, dealing with old pokemon image references

**Pull request merged**
