### PR TITLE
there are some missspells and small bugs, corrected

### PR DESCRIPTION
**Pull request by sanguneo**
try again, 
It's work for me.

### CODE REVIEW

**Comment by sanguneo** [comment]
It's look like conflicts are exist, please check and merge.
sorry again, there was miss spells and bugs.

**Comment by jjskuld** [comment]
Let me try to manually merge.

**Comment by sanguneo** [comment]
I've try resolve conflict.
try again.

and also RawDataJson.ts seems have error but, 
i've tried --force compile, fine.
and run also fine.

**Comment by jjskuld** [comment]
Thank you for this pull request.  I ended up backing out your changes and re-adding them one by one since I wasn't sure which change broke things. I was able to resolve all the issues including the RawDataJson.ts issue.

If possible could you do a hard-reset to master so that we are working from the same codebase again?  The master should have all of your changes (with the exception of some white-space changes).

**Comment by sanguneo** [comment]
I'll fork "https://github.com/Necrobot-Private/PokeEase" and remerge it again.
I think it will be fine.

**Pull request closed without merging**
